### ISSUE TITLE
Table T_IOT_xxxx not created

### ISSUE THREAD

**Issue by guillaumegarcia13** [SAP/iot-starterkit#1]
Same as http://scn.sap.com/docs/DOC-63811#comment-590831

I set up the application as explained.
Yet, it seems the table used for storing messages (and which follows the naming conventiion T_IOT_<DeviceTypeID>_<MessageTypeID>) are not created.
 
Am I missing something?
![iot](https://cloud.githubusercontent.com/assets/2786038/7797631/32b7bf96-02ef-11e5-8f28-49a922fcae1e.png)
 
Settings look OK
![iot settings](https://cloud.githubusercontent.com/assets/2786038/7797633/37bf9e6e-02ef-11e5-9e33-1472c204781a.PNG)
 
But no table...
![iot tables](https://cloud.githubusercontent.com/assets/2786038/7797634/3c0171aa-02ef-11e5-8695-8dd0abfdc374.PNG)
 
Event though they do share the same schema
![iot schema](https://cloud.githubusercontent.com/assets/2786038/7797635/4019ee20-02ef-11e5-9963-fb66e9fea7d3.PNG)
 
Thanks in advance.

**Comment by thomasjanke** [comment]
See: http://scn.sap.com/docs/DOC-63811#comment-590794

Tables will only be created after messages has been sent.
