### ISSUE TITLE
Looking for the real IoT hardware on the internet 

### ISSUE THREAD

**Issue by Pitkn** [SAP/iot-starterkit#25]
Hello,
 
I would like reconstruct the Raspberry Pi example and i'm looking for the suitable components on the internet. Can you help me to get the right IoT hardware? 

Regards,
PitKn

**Comment by levinanton** [comment]
Dear user,

GitHub "Issues" is not the right place for such discussions / questions. It is supposed to be a channel for reporting code / RT related issues with the underlying project. We, therefore, close it.

Best regards,
IoT StarterKit Team
