### ISSUE TITLE
Looking for the IoT Hardware for the Raspberry Pi example 

### ISSUE THREAD

**Issue by Pitkn** [SAP/iot-starterkit#26]
Hello, 

I write the same issues/question in the general GitHub "Issues" yesterday but that wasn't the right place. If this the wrong channel again please tell me where is the right place. 

My Question: I would like reconstruct the Raspberry Pi example and i'm looking for the suitable components on the internet. Can you help me to get the right IoT hardware? 

Best regards,
PitKn

**Comment by levinanton** [comment]
Dear user,

GitHub "Issues" is not the right place for such discussions / questions. It is supposed to be a channel for reporting code / RT related issues with the underlying project. We, therefore, close it.

Best regards,
IoT StarterKit Team

P.S. You may find necessary IoT hardware online by using Web Search Engines like Google or Bing and buy them from various online shops.
