### ISSUE TITLE
consumption-advanced failed with HTTP 404 when accessing iotrdms v2 api

### ISSUE THREAD

**Issue by commuter77** [SAP/iot-starterkit#37]
I tried consumption-advanced but failed. 
enclosed the screenshots.
it looks like the accessing the iotrdms v2 api via HCP destination failed.
https://webidetesting9968994-i029837trial.dispatcher.hanatrial.ondemand.com/iotrdms/v2/api/deviceTypes
I tried 
https://iotrdmsiotservices-i029837trial.hanatrial.ondemand.com/com.sap.iotservices.dms/v2/api/deviceTypes
it was successfull
can you advise ?

thanks & Best Regards,
Aaron
![iotrdms_v2_api_404](https://cloud.githubusercontent.com/assets/7900641/20202862/a29f678c-a7fd-11e6-9fa3-73bcc8636821.jpg)

**Comment by levinanton** [comment]
Hello Aaron, I failed to reproduce your issue with my trial account. If your direct link to RDMS works, could you please re-check what is specified in your "iotrdms" destination as URL? Check for typos, for example. In you case it should be https://iotrdmsiotservices-i029837trial.hanatrial.ondemand.com/com.sap.iotservices.dms 

Regards,
Anton

**Comment by commuter77** [comment]
Hi Anton,

I verified the following URL works fine in my browser.
https://iotrdmsiotservices-i029837trial.hanatrial.ondemand.com/com.sap.iotservices.dms/v2/api/messageTypes

then I copied 
https://iotrdmsiotservices-i029837trial.hanatrial.ondemand.com/com.sap.iotservices.dms
as the destination URL for "iotrdms" destination
I used “Check Connection" and it showed successfully.
I lauched the URL again in Chrome with incognito mode
https://webidetesting9968994-i029837trial.dispatcher.hanatrial.ondemand.com/src/webapp/index.html?hc_orionpath=%2Fi029837trial%24I029837-OrionContent%2Fodataconsumption&sap-ui-xx-componentPreload=off&origional-url=index.html&sap-ui-appCacheBuster=..%2F..%2F
the problem persisted.

I refreshed the Devices,
I can see the request sent to
https://webidetesting9968994-i029837trial.dispatcher.hanatrial.ondemand.com/iotrdms/v2/api/messageTypes
but again it is 404 error.
Is this request look correct ?
![404_error2](https://cloud.githubusercontent.com/assets/7900641/20209057/18084ae6-a82d-11e6-9eef-3ac1cf9615fd.jpg)

at the very beginning, the request sent to iotmms as well with 404 error.
https://webidetesting9968994-i029837trial.dispatcher.hanatrial.ondemand.com/iotmms/v1/api/http/app.svc/$metadata
but in the attached iotmms http access log, I could not find the request.

it looks like https://webidetesting9968994-i029837trial.dispatcher.hanatrial.ondemand.com/iotmms/
is not properly requested or anything wrong with 
webidetesting9968994-i029837trial.dispatcher.hanatrial.ondemand.com?
the request was not forwarded to the destination properly ?
[http_access_77e3bf3_2016-11-11_iotmms.zip](https://github.com/SAP/iot-starterkit/files/585341/http_access_77e3bf3_2016-11-11_iotmms.zip)

Should I contact the HCP team for help if so?

thanks & Best Regards,
Aaron

**Comment by commuter77** [comment]
I tried again it seems that the request did not come to iotmms.
is there anything wrong with my  Web IDE or the HCP problem？
enclosed the screenshots.
![requested_at_1655](https://cloud.githubusercontent.com/assets/7900641/20209638/62cc05a6-a830-11e6-9945-d64b09c5fc5a.jpg)
![http_access_iotmms_not_updated_at_1655](https://cloud.githubusercontent.com/assets/7900641/20209642/6b218730-a830-11e6-8b48-20b628a97d80.jpg)

**Comment by levinanton** [comment]
Seems to be a WebIDE problem specific to your account. From IoT Services perspective everything works as expected (you are able to access RDMS API directly). I would suggest to contact WebIDE team.
