### ISSUE TITLE
Access to the requested resource is not authorized (HTTP 401).

### ISSUE THREAD

**Issue by Pitkn** [SAP/iot-starterkit#39]
Hello,
I'm failed to use the Code-Snippets insert.py to send a message from a real IoT-Device to the SAP HANA Cloud Plattform. I can successfully test the HTTP API in the MMS with the same device, but when i use the insert.py i get the Error message "Access to the requested resource is not authorized (HTTP 401).". 

What can i do to solve this problem? 

thanks & Best Regards,
Pit

**Comment by levinanton** [comment]
Hello Pit, how does the URL which you try to reach look like? Line #19 in "insert.py" [1] script? Regards, Anton

[1] https://github.com/SAP/iot-starterkit/blob/master/src/code-snippets/python/hcp-iot-services/https/insert.py

**Comment by Pitkn** [comment]
I ask the question and finde the proböem at the same time. Thank for the quick reply.
The problem was to used to wrong AuthToken for the Device.

**Comment by SaiNithesh** [comment]
how can I get Auth Tokens for all the registered devices in one shot so that i want to change token based on the selected device.

**Comment by levinanton** [comment]
Hello @SaiNithesh there are no endpoints to get a token of the (registered) device (or tokens for all registered devices). The procedure is different. The one gets a device OAuth token at the point in time when device is being registered / onboarded. See more at [1]. A token can be re-newed afterwards [2]

Regards,
Anton

[1] https://help.sap.com/viewer/7436c3125dd5491f939689f18954b1e9/Cloud/en-US/65c78920d83f4e8cac6ac15e2aa07da0.html#loio1502078c22fb4e2d900dc844c9b9ff69
[2] https://help.sap.com/viewer/7436c3125dd5491f939689f18954b1e9/Cloud/en-US/65c78920d83f4e8cac6ac15e2aa07da0.html#loio3b7ea87e04f24c369a784321a66f1dd8
