### ISSUE TITLE
User credentials

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAP/iot-starterkit#48]
I think it would be worth mentioning that the user in encoded credentials should be [user]#[tenant]:[password]

Regards.
-Vitaliy

**Comment by dirkboerner** [comment]
Thanks Vitaliy for raising this issue. You are right, the credentials need for basic authentication should contain <userId>#<tenantId> as username. We will check if we need to adapt the documentation.

Best,
Dirk

**Comment by levinanton** [comment]
I am closing this now. Please, see 4.8 release notes for more details https://help.sap.com/viewer/a91b9b0c730241f99b6dd32fdc310a5b/Cloud/en-US
