### ISSUE TITLE
Error when sending message

### ISSUE THREAD

**Issue by guillaumegarcia13** [SAP/iot-starterkit#5]
When using the "Send message" or "Switch LED state", the application is displaying a "undefined" message.
If you look further (breakpoint in index.html in pushData function), this is due to the system being unable to log you on and requesting a SAML token.
![image](https://cloud.githubusercontent.com/assets/2786038/8393815/ad451cc2-1d20-11e5-91bb-4dddaebe206b.png)

This can be seen at this URL;
https://goo.gl/Yophea

Thanks in advance.

**Comment by indaco** [comment]
Hi,
Did you  to check the authorization for iotmms app?

the following steps described for Push API security in your account https://help.hana.ondemand.com/iot/frameset.htm?9da1c18f6ab947c58052f4d07498a654.html (Security section at the end of the page).

Regards

**Comment by guillaumegarcia13** [comment]
You made my night!
I as missing the following part from https://help.hana.ondemand.com/iot/frameset.htm?9da1c18f6ab947c58052f4d07498a654.html:
![image](https://cloud.githubusercontent.com/assets/2786038/8394087/70f89e20-1d29-11e5-84ed-22fe1dd231e8.png)

**Comment by akashkumar1987** [comment]
Is the error resolved ??
