### ISSUE TITLE
Missing info on adding message type to index.html

### ISSUE THREAD

**Issue by vanderborghta** [SAP/iot-starterkit#6]
Since the last update, the readme (for java app) no longer explains where you need to add your own message type, device type, ... to the index.html. This info is however key in getting the iot starter kit working.

Kind regards,
Annelies

**Comment by levinanton** [comment]
Hello Annelies, 

there is no more need to modify the index.html file, all registered devices/message types will be loaded from RDMS on the fly (via a new destination) and will be available for selection in the drop-down box from the UI.

Regards,
Anton

**Comment by vanderborghta** [comment]
Hello Anton,

I deployed the java app yesterday without changing anything, but when accessing the page, it was just blank. However, after editing the index.html and filling in the types, it works again.
So I feel like there is a problem with the java app then.

Kind regards,
Annelies

**Comment by levinanton** [comment]
There should be no place for adding the types in index.html anymore. 

May I please ask you to compare yours with the one from master branch https://github.com/SAP/iot-starterkit/blob/master/src/apps/java/consumption/com.sap.iot.starterkit.ui/src/main/webapp/index.html ?

Maybe browser cached the page (its old implementation), so try to clear that. 

I will re-check the setup on my side as well.

Thanks for your feedback,
Anton

**Comment by vanderborghta** [comment]
Hello Anton,

It is the same version. I edited in function "initModels" and there I've replaced the "none" for deviceId, deviceTypeId and messageTypeId for both models.

Kind regards,
Annelies

**Comment by levinanton** [comment]
Hello Annelies,

could you please follow the next steps:

- check if you have 2 destinations for your starter kit java app:
![destinations](https://cloud.githubusercontent.com/assets/12249110/9083288/ad71ead8-3b69-11e5-861a-1f0c138e6c34.png)
- add/modify your setup if required
- revert your changes to index.html file
- redeploy and restart the starter kit java app
- check if drop down lists are filled with device / message type data in UI (right top corner)
![select](https://cloud.githubusercontent.com/assets/12249110/9083287/ad6fdb80-3b69-11e5-911c-e6d42080de4e.png)

Thanks,
Anton

**Comment by levinanton** [comment]
Hello Annelies,

can you please let me know if an issue is fixed for you now?

Thanks,
Anton

**Comment by levinanton** [comment]
Dear user,

this ticket is inactive since September 7, 2015. We are therefore closing it.
If your issue still persists, please feel free to reopen this ticket for further processing. In case you were asked to provide additional information by the processor, please do so when reopening the ticket.

Best regards,
IoT StarterKit Team
