### ISSUE TITLE
Java Consumption app not displaying data from tables!

### ISSUE THREAD

**Issue by mpharsha** [SAP/iot-starterkit#76]
Hi,

I deployed Java consumption application as described in below link [1]
[1] [https://github.com/SAP/iot-starterkit/tree/master/neo/apps/java/consumption](url)

Using the Message Management Service (MMS) Cockpit I can send messages to a message management service and I can see the stored messages, using "Display stored messages" in the MMS Cockpit (for different devices and different message types).
After deploying and starting the iotstarterkit application I can access the application but I get blank for all the lists.
![image](https://user-images.githubusercontent.com/19683123/43518579-2f0ec15e-95aa-11e8-9565-ce9de2507cfe.png)

I have made below checks before posting here:
1. "starterkit" java app is bound to the same schema ID as "iotmms". They both have a <default> binding pointing to same schema(iotmmsschema) ID.
2. Destinations section of "starterkit" app.
"iotrdms" destination URL is
<https://iotrdmsiotservices-pxxxxtrial.hanatrial.ondemand.com/com.sap.iotservices.dms> (with trial suffix), User is <pXXX> (with no trial suffix) and Password is my SAP Cloud platform login password.
3. Destination section of "starterkit" app.
For "iotmms" destination:
URL is <https://iotmmspxxxxtrial.hanatrial.ondemand.com/com.sap.iotservices.mms> (with trial suffix), User is <pXXX> (with no trial suffix) and Password is my SAP Cloud platform login password.
4. In browser on executing below link, I get following devices.
<https://iotrdmsiotservices-pXXXXtrial.hanatrial.ondemand.com/com.sap.iotservices.dms/v1/api/devices>
[{"id":"5b6b0dc6-f5b9-4232-8bfc-10add9a295cd","name":"MyGrovePI","device_type":"90b08720c75d218ef422"}]
5.  I created device types, message types and devices via the IoT Services Cockpit (see below picture).
![image](https://user-images.githubusercontent.com/19683123/43520349-34a9331e-95b0-11e8-907e-4390c21b5f5b.png)

Can someone help me, what might be the problem?

Regards,
Harsha MP

**Comment by levinanton** [comment]
Discussion moved to SAP Community https://answers.sap.com/questions/582390/java-consumption-application-not-displaying-data-f.html (closing it here)
