### ISSUE TITLE
Nodejs Example for sendng data over mqtt

### ISSUE THREAD

**Issue by farminf** [SAP/iot-starterkit#77]
Hi,
Do you have any example of code for sending data to IoT 4.0 (cloud foundry) over MQTT?
Since there are some complication on the certificates.  
thanks

**Comment by levinanton** [comment]
Dear User, 

not for NodeJS but you may have a look under "cf/samples" directory [1] for java, python and curl examples.

Regards,
Anton

[1] https://github.com/SAP/iot-starterkit/tree/master/cf/samples
