### ISSUE TITLE
Data is not displayed

### ISSUE THREAD

**Issue by StefanAtgithub** [SAP/iot-starterkit#8]
Hi,
I tried to use the java application on my HCP trial account.
After selecting a device and a message type, no values are displayed. Using the development tools in Firefox, I can see, that json files with data from the data base tables are received. Any Idea why this data is not displayed on the web site?
Thanks you very much,
Stefan

**Comment by levinanton** [comment]
Hello Stefan,

I have just tried to pull, build and deploy the "starter kit" java app from scratch on my Trial. The version of the IoT MMS deployed in my account is "2.1.0". It worked (data is shown in UI chart) for 3 browsers:
- Chrome v. 45.0.2454.85
- FF v. 40.0.3
- IE v.11.0.9600.17959

Can you please check what versions you have? And also let me know what are the field names of your Message Type that you try to visualize? Be aware, that "value" and "timestamp" fields are mandatory for correct visualization (in case you do not modify the UI part yourself).

Regards,
Anton

**Comment by StefanAtgithub** [comment]
thanks. I did not use "value" and "timestamp". Now it works, after I changed it.
